[workspace]
members = [
    "crates/mps-formula",
    "crates/mps-core",
    "crates/mps-cosmos",
    "crates/mps-jni",
    "crates/mps-ffm",
    "crates/mps-test",
    "crates/mps-web",
    "crates/mps-build-common",
    "crates/mps-bindgen-macro",
    "crates/xtask"
]
resolver = "2"

[workspace.package]
version = "0.1.4"
edition = "2024"

[workspace.dependencies]
rapier3d = { package = "rapier3d-f64", version = "0.35.1", features = ["parallel"] }
ljni = { version = "0.21.0", package = "jni" }
parking_lot = "0.12.5"
hashbrown = "0.17.1"
smallvec = "1.15.2"
rayon = "1.12"
anvilkit = { version = "0.1", features = ["rapier"] }
bevy_ecs = { version = "0.14" }
dashmap = "6.1"

# Profile settings only take effect at the workspace root.
[profile.dev]
panic = "unwind"

[profile.release]
panic = "abort"
lto = "thin"
codegen-units = 1
opt-level = 3
strip = true
debug = 0