// Auto-generated by `cargo run -p xtask -- gen-java`. Do NOT edit by hand.
package org.polaris2023.mps.ffi;

import org.polaris2023.mps_rigid_body.util.NativeMemory;

public final class AabbDesc {
    public static final long SIZEOF = 48L;

    private final NativeMemory mem;
    private final long offset;

    public AabbDesc(NativeMemory mem, long offset) {
        this.mem = mem;
        this.offset = offset;
    }

    public static long sizeOf() {
        return SIZEOF;
    }

    public NativeMemory mem() {
        return mem;
    }

    public long offset() {
        return offset;
    }

    public Vec3 mins() {
        return new Vec3(mem, offset + 0L);
    }

    public void setMins(Vec3 value) {
        for (long k = 0L; k < 24L; k += 8L) {
            mem.putLong(offset + 0L + k, value.mem().getLong(value.offset() + k));
        }
    }

    public Vec3 maxs() {
        return new Vec3(mem, offset + 24L);
    }

    public void setMaxs(Vec3 value) {
        for (long k = 0L; k < 24L; k += 8L) {
            mem.putLong(offset + 24L + k, value.mem().getLong(value.offset() + k));
        }
    }

}
