// Auto-generated by `cargo run -p xtask -- gen-java`. Do NOT edit by hand.
package org.polaris2023.mps.ffi;

import org.polaris2023.mps_rigid_body.util.NativeMemory;

public final class AirDragLaw {
    public static final long SIZEOF = 80L;

    private final NativeMemory mem;
    private final long offset;

    public AirDragLaw(NativeMemory mem, long offset) {
        this.mem = mem;
        this.offset = offset;
    }

    public static long sizeOf() {
        return SIZEOF;
    }

    public NativeMemory mem() {
        return mem;
    }

    public long offset() {
        return offset;
    }

    public Vec3 fluidVelocity() {
        return new Vec3(mem, offset + 0L);
    }

    public void setFluidVelocity(Vec3 value) {
        for (long k = 0L; k < 24L; k += 8L) {
            mem.putLong(offset + 0L + k, value.mem().getLong(value.offset() + k));
        }
    }

    public double density() {
        return mem.getDouble(offset + 24L);
    }

    public void setDensity(double value) {
        mem.putDouble(offset + 24L, value);
    }

    public double dynamicViscosity() {
        return mem.getDouble(offset + 32L);
    }

    public void setDynamicViscosity(double value) {
        mem.putDouble(offset + 32L, value);
    }

    public double characteristicLength() {
        return mem.getDouble(offset + 40L);
    }

    public void setCharacteristicLength(double value) {
        mem.putDouble(offset + 40L, value);
    }

    public double referenceArea() {
        return mem.getDouble(offset + 48L);
    }

    public void setReferenceArea(double value) {
        mem.putDouble(offset + 48L, value);
    }

    public double dragCoefficient() {
        return mem.getDouble(offset + 56L);
    }

    public void setDragCoefficient(double value) {
        mem.putDouble(offset + 56L, value);
    }

    public double reynoldsStokesLimit() {
        return mem.getDouble(offset + 64L);
    }

    public void setReynoldsStokesLimit(double value) {
        mem.putDouble(offset + 64L, value);
    }

    public boolean enabled() {
        return mem.getBool(offset + 72L);
    }

    public void setEnabled(boolean value) {
        mem.putByte(offset + 72L, value ? 1 : 0);
    }

}
