// Auto-generated by `cargo run -p xtask -- gen-java`. Do NOT edit by hand.
package org.polaris2023.mps.ffi;

public final class BodyStatus {
    private BodyStatus() {}

    public static final int DYNAMIC = 0;
    public static final int FIXED = 1;
    public static final int KINEMATIC_POSITION_BASED = 2;
    public static final int KINEMATIC_VELOCITY_BASED = 3;

    public static int fromRaw(int raw) {
        return raw;
    }

    public static int toRaw(int value) {
        return value;
    }
}
