// Auto-generated by `cargo run -p xtask -- gen-java`. Do NOT edit by hand.
package org.polaris2023.mps.ffi;

import org.polaris2023.mps_rigid_body.util.NativeMemory;

public final class CharacterCollision {
    public static final long SIZEOF = 184L;

    private final NativeMemory mem;
    private final long offset;

    public CharacterCollision(NativeMemory mem, long offset) {
        this.mem = mem;
        this.offset = offset;
    }

    public static long sizeOf() {
        return SIZEOF;
    }

    public NativeMemory mem() {
        return mem;
    }

    public long offset() {
        return offset;
    }

    public long collider() {
        return mem.getLong(offset + 0L);
    }

    public void setCollider(long value) {
        mem.putLong(offset + 0L, value);
    }

    public Vec3 characterTranslation() {
        return new Vec3(mem, offset + 8L);
    }

    public void setCharacterTranslation(Vec3 value) {
        for (long k = 0L; k < 24L; k += 8L) {
            mem.putLong(offset + 8L + k, value.mem().getLong(value.offset() + k));
        }
    }

    public Vec3 translationApplied() {
        return new Vec3(mem, offset + 32L);
    }

    public void setTranslationApplied(Vec3 value) {
        for (long k = 0L; k < 24L; k += 8L) {
            mem.putLong(offset + 32L + k, value.mem().getLong(value.offset() + k));
        }
    }

    public Vec3 translationRemaining() {
        return new Vec3(mem, offset + 56L);
    }

    public void setTranslationRemaining(Vec3 value) {
        for (long k = 0L; k < 24L; k += 8L) {
            mem.putLong(offset + 56L + k, value.mem().getLong(value.offset() + k));
        }
    }

    public Vec3 worldWitness1() {
        return new Vec3(mem, offset + 80L);
    }

    public void setWorldWitness1(Vec3 value) {
        for (long k = 0L; k < 24L; k += 8L) {
            mem.putLong(offset + 80L + k, value.mem().getLong(value.offset() + k));
        }
    }

    public Vec3 worldWitness2() {
        return new Vec3(mem, offset + 104L);
    }

    public void setWorldWitness2(Vec3 value) {
        for (long k = 0L; k < 24L; k += 8L) {
            mem.putLong(offset + 104L + k, value.mem().getLong(value.offset() + k));
        }
    }

    public Vec3 normal1() {
        return new Vec3(mem, offset + 128L);
    }

    public void setNormal1(Vec3 value) {
        for (long k = 0L; k < 24L; k += 8L) {
            mem.putLong(offset + 128L + k, value.mem().getLong(value.offset() + k));
        }
    }

    public Vec3 normal2() {
        return new Vec3(mem, offset + 152L);
    }

    public void setNormal2(Vec3 value) {
        for (long k = 0L; k < 24L; k += 8L) {
            mem.putLong(offset + 152L + k, value.mem().getLong(value.offset() + k));
        }
    }

    public double timeOfImpact() {
        return mem.getDouble(offset + 176L);
    }

    public void setTimeOfImpact(double value) {
        mem.putDouble(offset + 176L, value);
    }

}
