// Auto-generated by `cargo run -p xtask -- gen-java`. Do NOT edit by hand.
package org.polaris2023.mps.ffi;

import org.polaris2023.mps_rigid_body.util.NativeMemory;

public final class CollisionEventRecord {
    public static final long SIZEOF = 32L;

    private final NativeMemory mem;
    private final long offset;

    public CollisionEventRecord(NativeMemory mem, long offset) {
        this.mem = mem;
        this.offset = offset;
    }

    public static long sizeOf() {
        return SIZEOF;
    }

    public NativeMemory mem() {
        return mem;
    }

    public long offset() {
        return offset;
    }

    public boolean started() {
        return mem.getBool(offset + 0L);
    }

    public void setStarted(boolean value) {
        mem.putByte(offset + 0L, value ? 1 : 0);
    }

    public long collider1() {
        return mem.getLong(offset + 8L);
    }

    public void setCollider1(long value) {
        mem.putLong(offset + 8L, value);
    }

    public long collider2() {
        return mem.getLong(offset + 16L);
    }

    public void setCollider2(long value) {
        mem.putLong(offset + 16L, value);
    }

    public boolean sensor() {
        return mem.getBool(offset + 24L);
    }

    public void setSensor(boolean value) {
        mem.putByte(offset + 24L, value ? 1 : 0);
    }

    public boolean removed() {
        return mem.getBool(offset + 25L);
    }

    public void setRemoved(boolean value) {
        mem.putByte(offset + 25L, value ? 1 : 0);
    }

}
