// Auto-generated by `cargo run -p xtask -- gen-java`. Do NOT edit by hand.
package org.polaris2023.mps.ffi;

import org.polaris2023.mps_rigid_body.util.NativeMemory;

public final class ContactForceEventRecord {
    public static final long SIZEOF = 80L;

    private final NativeMemory mem;
    private final long offset;

    public ContactForceEventRecord(NativeMemory mem, long offset) {
        this.mem = mem;
        this.offset = offset;
    }

    public static long sizeOf() {
        return SIZEOF;
    }

    public NativeMemory mem() {
        return mem;
    }

    public long offset() {
        return offset;
    }

    public long collider1() {
        return mem.getLong(offset + 0L);
    }

    public void setCollider1(long value) {
        mem.putLong(offset + 0L, value);
    }

    public long collider2() {
        return mem.getLong(offset + 8L);
    }

    public void setCollider2(long value) {
        mem.putLong(offset + 8L, value);
    }

    public Vec3 totalForce() {
        return new Vec3(mem, offset + 16L);
    }

    public void setTotalForce(Vec3 value) {
        for (long k = 0L; k < 24L; k += 8L) {
            mem.putLong(offset + 16L + k, value.mem().getLong(value.offset() + k));
        }
    }

    public double totalForceMagnitude() {
        return mem.getDouble(offset + 40L);
    }

    public void setTotalForceMagnitude(double value) {
        mem.putDouble(offset + 40L, value);
    }

    public Vec3 maxForceDirection() {
        return new Vec3(mem, offset + 48L);
    }

    public void setMaxForceDirection(Vec3 value) {
        for (long k = 0L; k < 24L; k += 8L) {
            mem.putLong(offset + 48L + k, value.mem().getLong(value.offset() + k));
        }
    }

    public double maxForceMagnitude() {
        return mem.getDouble(offset + 72L);
    }

    public void setMaxForceMagnitude(double value) {
        mem.putDouble(offset + 72L, value);
    }

}
