// Auto-generated by `cargo run -p xtask -- gen-java`. Do NOT edit by hand.
package org.polaris2023.mps.ffi;

import org.polaris2023.mps_rigid_body.util.NativeMemory;

public final class DynamicalFrictionLaw {
    public static final long SIZEOF = 24L;

    private final NativeMemory mem;
    private final long offset;

    public DynamicalFrictionLaw(NativeMemory mem, long offset) {
        this.mem = mem;
        this.offset = offset;
    }

    public static long sizeOf() {
        return SIZEOF;
    }

    public NativeMemory mem() {
        return mem;
    }

    public long offset() {
        return offset;
    }

    public double backgroundDensityKgM3() {
        return mem.getDouble(offset + 0L);
    }

    public void setBackgroundDensityKgM3(double value) {
        mem.putDouble(offset + 0L, value);
    }

    public double coulombLog() {
        return mem.getDouble(offset + 8L);
    }

    public void setCoulombLog(double value) {
        mem.putDouble(offset + 8L, value);
    }

    public boolean enabled() {
        return mem.getBool(offset + 16L);
    }

    public void setEnabled(boolean value) {
        mem.putByte(offset + 16L, value ? 1 : 0);
    }

}
