// Auto-generated by `cargo run -p xtask -- gen-java`. Do NOT edit by hand.
package org.polaris2023.mps.ffi;

import org.polaris2023.mps_rigid_body.util.NativeMemory;

public final class Ellipsoid {
    public static final long SIZEOF = 88L;

    private final NativeMemory mem;
    private final long offset;

    public Ellipsoid(NativeMemory mem, long offset) {
        this.mem = mem;
        this.offset = offset;
    }

    public static long sizeOf() {
        return SIZEOF;
    }

    public NativeMemory mem() {
        return mem;
    }

    public long offset() {
        return offset;
    }

    public Vec3 center() {
        return new Vec3(mem, offset + 0L);
    }

    public void setCenter(Vec3 value) {
        for (long k = 0L; k < 24L; k += 8L) {
            mem.putLong(offset + 0L + k, value.mem().getLong(value.offset() + k));
        }
    }

    public Vec3 radii() {
        return new Vec3(mem, offset + 24L);
    }

    public void setRadii(Vec3 value) {
        for (long k = 0L; k < 24L; k += 8L) {
            mem.putLong(offset + 24L + k, value.mem().getLong(value.offset() + k));
        }
    }

    public Quat rotation() {
        return new Quat(mem, offset + 48L);
    }

    public void setRotation(Quat value) {
        for (long k = 0L; k < 32L; k += 8L) {
            mem.putLong(offset + 48L + k, value.mem().getLong(value.offset() + k));
        }
    }

    public int segments() {
        return mem.getInt(offset + 80L);
    }

    public void setSegments(int value) {
        mem.putInt(offset + 80L, value);
    }

}
