// Auto-generated by `cargo run -p xtask -- gen-java`. Do NOT edit by hand.
package org.polaris2023.mps.ffi;

import org.polaris2023.mps_rigid_body.util.NativeMemory;

public final class ExternalForceLaw {
    public static final long SIZEOF = 208L;

    private final NativeMemory mem;
    private final long offset;

    public ExternalForceLaw(NativeMemory mem, long offset) {
        this.mem = mem;
        this.offset = offset;
    }

    public static long sizeOf() {
        return SIZEOF;
    }

    public NativeMemory mem() {
        return mem;
    }

    public long offset() {
        return offset;
    }

    public boolean buoyancyEnabled() {
        return mem.getBool(offset + 0L);
    }

    public void setBuoyancyEnabled(boolean value) {
        mem.putByte(offset + 0L, value ? 1 : 0);
    }

    public double fluidDensity() {
        return mem.getDouble(offset + 8L);
    }

    public void setFluidDensity(double value) {
        mem.putDouble(offset + 8L, value);
    }

    public double displacedVolume() {
        return mem.getDouble(offset + 16L);
    }

    public void setDisplacedVolume(double value) {
        mem.putDouble(offset + 16L, value);
    }

    public Vec3 buoyancyGravity() {
        return new Vec3(mem, offset + 24L);
    }

    public void setBuoyancyGravity(Vec3 value) {
        for (long k = 0L; k < 24L; k += 8L) {
            mem.putLong(offset + 24L + k, value.mem().getLong(value.offset() + k));
        }
    }

    public boolean electromagneticEnabled() {
        return mem.getBool(offset + 48L);
    }

    public void setElectromagneticEnabled(boolean value) {
        mem.putByte(offset + 48L, value ? 1 : 0);
    }

    public double charge() {
        return mem.getDouble(offset + 56L);
    }

    public void setCharge(double value) {
        mem.putDouble(offset + 56L, value);
    }

    public Vec3 electricField() {
        return new Vec3(mem, offset + 64L);
    }

    public void setElectricField(Vec3 value) {
        for (long k = 0L; k < 24L; k += 8L) {
            mem.putLong(offset + 64L + k, value.mem().getLong(value.offset() + k));
        }
    }

    public Vec3 magneticField() {
        return new Vec3(mem, offset + 88L);
    }

    public void setMagneticField(Vec3 value) {
        for (long k = 0L; k < 24L; k += 8L) {
            mem.putLong(offset + 88L + k, value.mem().getLong(value.offset() + k));
        }
    }

    public boolean elasticEnabled() {
        return mem.getBool(offset + 112L);
    }

    public void setElasticEnabled(boolean value) {
        mem.putByte(offset + 112L, value ? 1 : 0);
    }

    public Vec3 springAnchor() {
        return new Vec3(mem, offset + 120L);
    }

    public void setSpringAnchor(Vec3 value) {
        for (long k = 0L; k < 24L; k += 8L) {
            mem.putLong(offset + 120L + k, value.mem().getLong(value.offset() + k));
        }
    }

    public double springStiffness() {
        return mem.getDouble(offset + 144L);
    }

    public void setSpringStiffness(double value) {
        mem.putDouble(offset + 144L, value);
    }

    public double springDamping() {
        return mem.getDouble(offset + 152L);
    }

    public void setSpringDamping(double value) {
        mem.putDouble(offset + 152L, value);
    }

    public boolean gravityEnabled() {
        return mem.getBool(offset + 160L);
    }

    public void setGravityEnabled(boolean value) {
        mem.putByte(offset + 160L, value ? 1 : 0);
    }

    public Vec3 gravitySource() {
        return new Vec3(mem, offset + 168L);
    }

    public void setGravitySource(Vec3 value) {
        for (long k = 0L; k < 24L; k += 8L) {
            mem.putLong(offset + 168L + k, value.mem().getLong(value.offset() + k));
        }
    }

    public double gravitationalParameter() {
        return mem.getDouble(offset + 192L);
    }

    public void setGravitationalParameter(double value) {
        mem.putDouble(offset + 192L, value);
    }

    public boolean enabled() {
        return mem.getBool(offset + 200L);
    }

    public void setEnabled(boolean value) {
        mem.putByte(offset + 200L, value ? 1 : 0);
    }

}
