// Auto-generated by `cargo run -p xtask -- gen-java`. Do NOT edit by hand.
package org.polaris2023.mps.ffi;

import org.polaris2023.mps_rigid_body.util.NativeMemory;

public final class InteractionGroupsDesc {
    public static final long SIZEOF = 8L;

    private final NativeMemory mem;
    private final long offset;

    public InteractionGroupsDesc(NativeMemory mem, long offset) {
        this.mem = mem;
        this.offset = offset;
    }

    public static long sizeOf() {
        return SIZEOF;
    }

    public NativeMemory mem() {
        return mem;
    }

    public long offset() {
        return offset;
    }

    public int memberships() {
        return mem.getInt(offset + 0L);
    }

    public void setMemberships(int value) {
        mem.putInt(offset + 0L, value);
    }

    public int filter() {
        return mem.getInt(offset + 4L);
    }

    public void setFilter(int value) {
        mem.putInt(offset + 4L, value);
    }

}
