// Auto-generated by `cargo run -p xtask -- gen-java`. Do NOT edit by hand.
package org.polaris2023.mps.ffi;

import org.polaris2023.mps_rigid_body.util.NativeMemory;

public final class JeansEscapeLaw {
    public static final long SIZEOF = 72L;

    private final NativeMemory mem;
    private final long offset;

    public JeansEscapeLaw(NativeMemory mem, long offset) {
        this.mem = mem;
        this.offset = offset;
    }

    public static long sizeOf() {
        return SIZEOF;
    }

    public NativeMemory mem() {
        return mem;
    }

    public long offset() {
        return offset;
    }

    public double nExo() {
        return mem.getDouble(offset + 0L);
    }

    public void setNExo(double value) {
        mem.putDouble(offset + 0L, value);
    }

    public double temperature() {
        return mem.getDouble(offset + 8L);
    }

    public void setTemperature(double value) {
        mem.putDouble(offset + 8L, value);
    }

    public double escapeParameter() {
        return mem.getDouble(offset + 16L);
    }

    public void setEscapeParameter(double value) {
        mem.putDouble(offset + 16L, value);
    }

    public double massKg() {
        return mem.getDouble(offset + 24L);
    }

    public void setMassKg(double value) {
        mem.putDouble(offset + 24L, value);
    }

    public Vec3 escapeDirection() {
        return new Vec3(mem, offset + 32L);
    }

    public void setEscapeDirection(Vec3 value) {
        for (long k = 0L; k < 24L; k += 8L) {
            mem.putLong(offset + 32L + k, value.mem().getLong(value.offset() + k));
        }
    }

    public double effectiveAreaM2() {
        return mem.getDouble(offset + 56L);
    }

    public void setEffectiveAreaM2(double value) {
        mem.putDouble(offset + 56L, value);
    }

    public boolean enabled() {
        return mem.getBool(offset + 64L);
    }

    public void setEnabled(boolean value) {
        mem.putByte(offset + 64L, value ? 1 : 0);
    }

}
