// Auto-generated by `cargo run -p xtask -- gen-java`. Do NOT edit by hand.
package org.polaris2023.mps.ffi;

public final class KdopPreset {
    private KdopPreset() {}

    public static final int K6 = 6;
    public static final int K14 = 14;
    public static final int K18 = 18;
    public static final int K26 = 26;

    public static int fromRaw(int raw) {
        return raw;
    }

    public static int toRaw(int value) {
        return value;
    }
}
