// Auto-generated by `cargo run -p xtask -- gen-java`. Do NOT edit by hand.
package org.polaris2023.mps.ffi;

import org.polaris2023.mps_rigid_body.util.NativeMemory;

public final class MonDGravityLaw {
    public static final long SIZEOF = 48L;

    private final NativeMemory mem;
    private final long offset;

    public MonDGravityLaw(NativeMemory mem, long offset) {
        this.mem = mem;
        this.offset = offset;
    }

    public static long sizeOf() {
        return SIZEOF;
    }

    public NativeMemory mem() {
        return mem;
    }

    public long offset() {
        return offset;
    }

    public double newtonianA() {
        return mem.getDouble(offset + 0L);
    }

    public void setNewtonianA(double value) {
        mem.putDouble(offset + 0L, value);
    }

    public double mondAZero() {
        return mem.getDouble(offset + 8L);
    }

    public void setMondAZero(double value) {
        mem.putDouble(offset + 8L, value);
    }

    public Vec3 direction() {
        return new Vec3(mem, offset + 16L);
    }

    public void setDirection(Vec3 value) {
        for (long k = 0L; k < 24L; k += 8L) {
            mem.putLong(offset + 16L + k, value.mem().getLong(value.offset() + k));
        }
    }

    public boolean enabled() {
        return mem.getBool(offset + 40L);
    }

    public void setEnabled(boolean value) {
        mem.putByte(offset + 40L, value ? 1 : 0);
    }

}
