// Auto-generated by `cargo run -p xtask -- gen-java`. Do NOT edit by hand.
package org.polaris2023.mps.ffi;

import org.polaris2023.mps_rigid_body.util.NativeMemory;

public final class NeuralBoundsDesc {
    public static final long SIZEOF = 112L;

    private final NativeMemory mem;
    private final long offset;

    public NeuralBoundsDesc(NativeMemory mem, long offset) {
        this.mem = mem;
        this.offset = offset;
    }

    public static long sizeOf() {
        return SIZEOF;
    }

    public NativeMemory mem() {
        return mem;
    }

    public long offset() {
        return offset;
    }

    public Vec3 center() {
        return new Vec3(mem, offset + 0L);
    }

    public void setCenter(Vec3 value) {
        for (long k = 0L; k < 24L; k += 8L) {
            mem.putLong(offset + 0L + k, value.mem().getLong(value.offset() + k));
        }
    }

    public Vec3 halfExtents() {
        return new Vec3(mem, offset + 24L);
    }

    public void setHalfExtents(Vec3 value) {
        for (long k = 0L; k < 24L; k += 8L) {
            mem.putLong(offset + 24L + k, value.mem().getLong(value.offset() + k));
        }
    }

    public Quat rotation() {
        return new Quat(mem, offset + 48L);
    }

    public void setRotation(Quat value) {
        for (long k = 0L; k < 32L; k += 8L) {
            mem.putLong(offset + 48L + k, value.mem().getLong(value.offset() + k));
        }
    }

    public int sampleResolution() {
        return mem.getInt(offset + 80L);
    }

    public void setSampleResolution(int value) {
        mem.putInt(offset + 80L, value);
    }

    public int hiddenWidth() {
        return mem.getInt(offset + 84L);
    }

    public void setHiddenWidth(int value) {
        mem.putInt(offset + 84L, value);
    }

    public int hiddenLayers() {
        return mem.getInt(offset + 88L);
    }

    public void setHiddenLayers(int value) {
        mem.putInt(offset + 88L, value);
    }

    public int activation() {
        return mem.getInt(offset + 92L);
    }

    public void setActivation(int value) {
        mem.putInt(offset + 92L, value);
    }

    public double outputScale() {
        return mem.getDouble(offset + 96L);
    }

    public void setOutputScale(double value) {
        mem.putDouble(offset + 96L, value);
    }

    public double padding() {
        return mem.getDouble(offset + 104L);
    }

    public void setPadding(double value) {
        mem.putDouble(offset + 104L, value);
    }

}
