// Auto-generated by `cargo run -p xtask -- gen-java`. Do NOT edit by hand.
package org.polaris2023.mps.ffi;

public final class NeuralActivation {
    private NeuralActivation() {}

    public static final int RELU = 0;
    public static final int TANH = 1;
    public static final int SIN = 2;
    public static final int LINEAR = 3;

    public static int fromRaw(int raw) {
        return raw;
    }

    public static int toRaw(int value) {
        return value;
    }
}
