// Auto-generated by `cargo run -p xtask -- gen-java`. Do NOT edit by hand.
package org.polaris2023.mps.ffi;

import org.polaris2023.mps_rigid_body.util.NativeMemory;

public final class NewtonGravityLaw {
    public static final long SIZEOF = 32L;

    private final NativeMemory mem;
    private final long offset;

    public NewtonGravityLaw(NativeMemory mem, long offset) {
        this.mem = mem;
        this.offset = offset;
    }

    public static long sizeOf() {
        return SIZEOF;
    }

    public NativeMemory mem() {
        return mem;
    }

    public long offset() {
        return offset;
    }

    public double gravitationalConstant() {
        return mem.getDouble(offset + 0L);
    }

    public void setGravitationalConstant(double value) {
        mem.putDouble(offset + 0L, value);
    }

    public double minDistance() {
        return mem.getDouble(offset + 8L);
    }

    public void setMinDistance(double value) {
        mem.putDouble(offset + 8L, value);
    }

    public double maxDistance() {
        return mem.getDouble(offset + 16L);
    }

    public void setMaxDistance(double value) {
        mem.putDouble(offset + 16L, value);
    }

    public boolean enabled() {
        return mem.getBool(offset + 24L);
    }

    public void setEnabled(boolean value) {
        mem.putByte(offset + 24L, value ? 1 : 0);
    }

}
