// Auto-generated by `cargo run -p xtask -- gen-java`. Do NOT edit by hand.
package org.polaris2023.mps.ffi;

import org.polaris2023.mps_rigid_body.util.NativeMemory;

public final class Prism {
    public static final long SIZEOF = 80L;

    private final NativeMemory mem;
    private final long offset;

    public Prism(NativeMemory mem, long offset) {
        this.mem = mem;
        this.offset = offset;
    }

    public static long sizeOf() {
        return SIZEOF;
    }

    public NativeMemory mem() {
        return mem;
    }

    public long offset() {
        return offset;
    }

    public Vec3 center() {
        return new Vec3(mem, offset + 0L);
    }

    public void setCenter(Vec3 value) {
        for (long k = 0L; k < 24L; k += 8L) {
            mem.putLong(offset + 0L + k, value.mem().getLong(value.offset() + k));
        }
    }

    public double radius() {
        return mem.getDouble(offset + 24L);
    }

    public void setRadius(double value) {
        mem.putDouble(offset + 24L, value);
    }

    public double halfHeight() {
        return mem.getDouble(offset + 32L);
    }

    public void setHalfHeight(double value) {
        mem.putDouble(offset + 32L, value);
    }

    public int sides() {
        return mem.getInt(offset + 40L);
    }

    public void setSides(int value) {
        mem.putInt(offset + 40L, value);
    }

    public Quat rotation() {
        return new Quat(mem, offset + 48L);
    }

    public void setRotation(Quat value) {
        for (long k = 0L; k < 32L; k += 8L) {
            mem.putLong(offset + 48L + k, value.mem().getLong(value.offset() + k));
        }
    }

}
