// Auto-generated by `cargo run -p xtask -- gen-java`. Do NOT edit by hand.
package org.polaris2023.mps.ffi;

import org.polaris2023.mps_rigid_body.util.NativeMemory;

public final class PulsarMagneticDipoleLaw {
    public static final long SIZEOF = 112L;

    private final NativeMemory mem;
    private final long offset;

    public PulsarMagneticDipoleLaw(NativeMemory mem, long offset) {
        this.mem = mem;
        this.offset = offset;
    }

    public static long sizeOf() {
        return SIZEOF;
    }

    public NativeMemory mem() {
        return mem;
    }

    public long offset() {
        return offset;
    }

    public double momentOfInertia() {
        return mem.getDouble(offset + 0L);
    }

    public void setMomentOfInertia(double value) {
        mem.putDouble(offset + 0L, value);
    }

    public double nsRadiusM() {
        return mem.getDouble(offset + 8L);
    }

    public void setNsRadiusM(double value) {
        mem.putDouble(offset + 8L, value);
    }

    public double periodMs() {
        return mem.getDouble(offset + 16L);
    }

    public void setPeriodMs(double value) {
        mem.putDouble(offset + 16L, value);
    }

    public double periodDerivative() {
        return mem.getDouble(offset + 24L);
    }

    public void setPeriodDerivative(double value) {
        mem.putDouble(offset + 24L, value);
    }

    public Vec3 pulsarPosition() {
        return new Vec3(mem, offset + 32L);
    }

    public void setPulsarPosition(Vec3 value) {
        for (long k = 0L; k < 24L; k += 8L) {
            mem.putLong(offset + 32L + k, value.mem().getLong(value.offset() + k));
        }
    }

    public Vec3 spinAxis() {
        return new Vec3(mem, offset + 56L);
    }

    public void setSpinAxis(Vec3 value) {
        for (long k = 0L; k < 24L; k += 8L) {
            mem.putLong(offset + 56L + k, value.mem().getLong(value.offset() + k));
        }
    }

    public Vec3 bodyDipoleMoment() {
        return new Vec3(mem, offset + 80L);
    }

    public void setBodyDipoleMoment(Vec3 value) {
        for (long k = 0L; k < 24L; k += 8L) {
            mem.putLong(offset + 80L + k, value.mem().getLong(value.offset() + k));
        }
    }

    public boolean enabled() {
        return mem.getBool(offset + 104L);
    }

    public void setEnabled(boolean value) {
        mem.putByte(offset + 104L, value ? 1 : 0);
    }

}
