// Auto-generated by `cargo run -p xtask -- gen-java`. Do NOT edit by hand.
package org.polaris2023.mps.ffi;

import org.polaris2023.mps_rigid_body.util.NativeMemory;

public final class Quat {
    public static final long SIZEOF = 32L;

    private final NativeMemory mem;
    private final long offset;

    public Quat(NativeMemory mem, long offset) {
        this.mem = mem;
        this.offset = offset;
    }

    public static long sizeOf() {
        return SIZEOF;
    }

    public NativeMemory mem() {
        return mem;
    }

    public long offset() {
        return offset;
    }

    public double i() {
        return mem.getDouble(offset + 0L);
    }

    public void setI(double value) {
        mem.putDouble(offset + 0L, value);
    }

    public double j() {
        return mem.getDouble(offset + 8L);
    }

    public void setJ(double value) {
        mem.putDouble(offset + 8L, value);
    }

    public double k() {
        return mem.getDouble(offset + 16L);
    }

    public void setK(double value) {
        mem.putDouble(offset + 16L, value);
    }

    public double w() {
        return mem.getDouble(offset + 24L);
    }

    public void setW(double value) {
        mem.putDouble(offset + 24L, value);
    }

}
