// Auto-generated by `cargo run -p xtask -- gen-java`. Do NOT edit by hand.
package org.polaris2023.mps.ffi;

import org.polaris2023.mps_rigid_body.util.NativeMemory;

public final class QueryFilterDesc {
    public static final long SIZEOF = 48L;

    private final NativeMemory mem;
    private final long offset;

    public QueryFilterDesc(NativeMemory mem, long offset) {
        this.mem = mem;
        this.offset = offset;
    }

    public static long sizeOf() {
        return SIZEOF;
    }

    public NativeMemory mem() {
        return mem;
    }

    public long offset() {
        return offset;
    }

    public int flags() {
        return mem.getInt(offset + 0L);
    }

    public void setFlags(int value) {
        mem.putInt(offset + 0L, value);
    }

    public InteractionGroupsDesc groups() {
        return new InteractionGroupsDesc(mem, offset + 4L);
    }

    public void setGroups(InteractionGroupsDesc value) {
        for (long k = 0L; k < 8L; k += 8L) {
            mem.putLong(offset + 4L + k, value.mem().getLong(value.offset() + k));
        }
    }

    public boolean useGroups() {
        return mem.getBool(offset + 12L);
    }

    public void setUseGroups(boolean value) {
        mem.putByte(offset + 12L, value ? 1 : 0);
    }

    public long excludeCollider() {
        return mem.getLong(offset + 16L);
    }

    public void setExcludeCollider(long value) {
        mem.putLong(offset + 16L, value);
    }

    public boolean useExcludeCollider() {
        return mem.getBool(offset + 24L);
    }

    public void setUseExcludeCollider(boolean value) {
        mem.putByte(offset + 24L, value ? 1 : 0);
    }

    public long excludeRigidBody() {
        return mem.getLong(offset + 32L);
    }

    public void setExcludeRigidBody(long value) {
        mem.putLong(offset + 32L, value);
    }

    public boolean useExcludeRigidBody() {
        return mem.getBool(offset + 40L);
    }

    public void setUseExcludeRigidBody(boolean value) {
        mem.putByte(offset + 40L, value ? 1 : 0);
    }

}
