// Auto-generated by `cargo run -p xtask -- gen-java`. Do NOT edit by hand.
package org.polaris2023.mps.ffi;

import org.polaris2023.mps_rigid_body.util.NativeMemory;

public final class RayHit {
    public static final long SIZEOF = 48L;

    private final NativeMemory mem;
    private final long offset;

    public RayHit(NativeMemory mem, long offset) {
        this.mem = mem;
        this.offset = offset;
    }

    public static long sizeOf() {
        return SIZEOF;
    }

    public NativeMemory mem() {
        return mem;
    }

    public long offset() {
        return offset;
    }

    public long collider() {
        return mem.getLong(offset + 0L);
    }

    public void setCollider(long value) {
        mem.putLong(offset + 0L, value);
    }

    public double timeOfImpact() {
        return mem.getDouble(offset + 8L);
    }

    public void setTimeOfImpact(double value) {
        mem.putDouble(offset + 8L, value);
    }

    public Vec3 normal() {
        return new Vec3(mem, offset + 16L);
    }

    public void setNormal(Vec3 value) {
        for (long k = 0L; k < 24L; k += 8L) {
            mem.putLong(offset + 16L + k, value.mem().getLong(value.offset() + k));
        }
    }

    public int feature() {
        return mem.getInt(offset + 40L);
    }

    public void setFeature(int value) {
        mem.putInt(offset + 40L, value);
    }

}
