// Auto-generated by `cargo run -p xtask -- gen-java`. Do NOT edit by hand.
package org.polaris2023.mps.ffi;

import org.polaris2023.mps_rigid_body.util.NativeMemory;

public final class ShapeCastOptionsDesc {
    public static final long SIZEOF = 24L;

    private final NativeMemory mem;
    private final long offset;

    public ShapeCastOptionsDesc(NativeMemory mem, long offset) {
        this.mem = mem;
        this.offset = offset;
    }

    public static long sizeOf() {
        return SIZEOF;
    }

    public NativeMemory mem() {
        return mem;
    }

    public long offset() {
        return offset;
    }

    public double maxTimeOfImpact() {
        return mem.getDouble(offset + 0L);
    }

    public void setMaxTimeOfImpact(double value) {
        mem.putDouble(offset + 0L, value);
    }

    public double targetDistance() {
        return mem.getDouble(offset + 8L);
    }

    public void setTargetDistance(double value) {
        mem.putDouble(offset + 8L, value);
    }

    public boolean stopAtPenetration() {
        return mem.getBool(offset + 16L);
    }

    public void setStopAtPenetration(boolean value) {
        mem.putByte(offset + 16L, value ? 1 : 0);
    }

    public boolean computeImpactGeometryOnPenetration() {
        return mem.getBool(offset + 17L);
    }

    public void setComputeImpactGeometryOnPenetration(boolean value) {
        mem.putByte(offset + 17L, value ? 1 : 0);
    }

}
