// Auto-generated by `cargo run -p xtask -- gen-java`. Do NOT edit by hand.
package org.polaris2023.mps.ffi;

public final class ShapeType {
    private ShapeType() {}

    public static final int BALL = 0;
    public static final int CUBOID = 1;
    public static final int CAPSULE_Y = 2;
    public static final int CAPSULE_X = 3;
    public static final int CAPSULE_Z = 4;
    public static final int CYLINDER = 5;
    public static final int ROUND_CYLINDER = 6;
    public static final int CONE = 7;
    public static final int ROUND_CONE = 8;
    public static final int ROUND_CUBOID = 9;

    public static int fromRaw(int raw) {
        return raw;
    }

    public static int toRaw(int value) {
        return value;
    }
}
