// Auto-generated by `cargo run -p xtask -- gen-java`. Do NOT edit by hand.
package org.polaris2023.mps.ffi;

import org.polaris2023.mps_rigid_body.util.NativeMemory;

public final class ShapeCastHit {
    public static final long SIZEOF = 120L;

    private final NativeMemory mem;
    private final long offset;

    public ShapeCastHit(NativeMemory mem, long offset) {
        this.mem = mem;
        this.offset = offset;
    }

    public static long sizeOf() {
        return SIZEOF;
    }

    public NativeMemory mem() {
        return mem;
    }

    public long offset() {
        return offset;
    }

    public long collider() {
        return mem.getLong(offset + 0L);
    }

    public void setCollider(long value) {
        mem.putLong(offset + 0L, value);
    }

    public double timeOfImpact() {
        return mem.getDouble(offset + 8L);
    }

    public void setTimeOfImpact(double value) {
        mem.putDouble(offset + 8L, value);
    }

    public Vec3 witness1() {
        return new Vec3(mem, offset + 16L);
    }

    public void setWitness1(Vec3 value) {
        for (long k = 0L; k < 24L; k += 8L) {
            mem.putLong(offset + 16L + k, value.mem().getLong(value.offset() + k));
        }
    }

    public Vec3 witness2() {
        return new Vec3(mem, offset + 40L);
    }

    public void setWitness2(Vec3 value) {
        for (long k = 0L; k < 24L; k += 8L) {
            mem.putLong(offset + 40L + k, value.mem().getLong(value.offset() + k));
        }
    }

    public Vec3 normal1() {
        return new Vec3(mem, offset + 64L);
    }

    public void setNormal1(Vec3 value) {
        for (long k = 0L; k < 24L; k += 8L) {
            mem.putLong(offset + 64L + k, value.mem().getLong(value.offset() + k));
        }
    }

    public Vec3 normal2() {
        return new Vec3(mem, offset + 88L);
    }

    public void setNormal2(Vec3 value) {
        for (long k = 0L; k < 24L; k += 8L) {
            mem.putLong(offset + 88L + k, value.mem().getLong(value.offset() + k));
        }
    }

    public int status() {
        return mem.getInt(offset + 112L);
    }

    public void setStatus(int value) {
        mem.putInt(offset + 112L, value);
    }

}
