// Auto-generated by `cargo run -p xtask -- gen-java`. Do NOT edit by hand.
package org.polaris2023.mps.ffi;

import org.polaris2023.mps_rigid_body.util.NativeMemory;

public final class ShapeDesc {
    public static final long SIZEOF = 40L;

    private final NativeMemory mem;
    private final long offset;

    public ShapeDesc(NativeMemory mem, long offset) {
        this.mem = mem;
        this.offset = offset;
    }

    public static long sizeOf() {
        return SIZEOF;
    }

    public NativeMemory mem() {
        return mem;
    }

    public long offset() {
        return offset;
    }

    public int shapeType() {
        return mem.getInt(offset + 0L);
    }

    public void setShapeType(int value) {
        mem.putInt(offset + 0L, value);
    }

    public double a() {
        return mem.getDouble(offset + 8L);
    }

    public void setA(double value) {
        mem.putDouble(offset + 8L, value);
    }

    public double b() {
        return mem.getDouble(offset + 16L);
    }

    public void setB(double value) {
        mem.putDouble(offset + 16L, value);
    }

    public double c() {
        return mem.getDouble(offset + 24L);
    }

    public void setC(double value) {
        mem.putDouble(offset + 24L, value);
    }

    public double d() {
        return mem.getDouble(offset + 32L);
    }

    public void setD(double value) {
        mem.putDouble(offset + 32L, value);
    }

}
