// Auto-generated by `cargo run -p xtask -- gen-java`. Do NOT edit by hand.
package org.polaris2023.mps.ffi;

import org.polaris2023.mps_rigid_body.util.NativeMemory;

public final class SphericalShell {
    public static final long SIZEOF = 40L;

    private final NativeMemory mem;
    private final long offset;

    public SphericalShell(NativeMemory mem, long offset) {
        this.mem = mem;
        this.offset = offset;
    }

    public static long sizeOf() {
        return SIZEOF;
    }

    public NativeMemory mem() {
        return mem;
    }

    public long offset() {
        return offset;
    }

    public Vec3 center() {
        return new Vec3(mem, offset + 0L);
    }

    public void setCenter(Vec3 value) {
        for (long k = 0L; k < 24L; k += 8L) {
            mem.putLong(offset + 0L + k, value.mem().getLong(value.offset() + k));
        }
    }

    public double innerRadius() {
        return mem.getDouble(offset + 24L);
    }

    public void setInnerRadius(double value) {
        mem.putDouble(offset + 24L, value);
    }

    public double outerRadius() {
        return mem.getDouble(offset + 32L);
    }

    public void setOuterRadius(double value) {
        mem.putDouble(offset + 32L, value);
    }

}
