// Auto-generated by `cargo run -p xtask -- gen-java`. Do NOT edit by hand.
package org.polaris2023.mps.ffi;

import org.polaris2023.mps_rigid_body.util.NativeMemory;

public final class Ssv {
    public static final long SIZEOF = 56L;

    private final NativeMemory mem;
    private final long offset;

    public Ssv(NativeMemory mem, long offset) {
        this.mem = mem;
        this.offset = offset;
    }

    public static long sizeOf() {
        return SIZEOF;
    }

    public NativeMemory mem() {
        return mem;
    }

    public long offset() {
        return offset;
    }

    public Vec3 a() {
        return new Vec3(mem, offset + 0L);
    }

    public void setA(Vec3 value) {
        for (long k = 0L; k < 24L; k += 8L) {
            mem.putLong(offset + 0L + k, value.mem().getLong(value.offset() + k));
        }
    }

    public Vec3 b() {
        return new Vec3(mem, offset + 24L);
    }

    public void setB(Vec3 value) {
        for (long k = 0L; k < 24L; k += 8L) {
            mem.putLong(offset + 24L + k, value.mem().getLong(value.offset() + k));
        }
    }

    public double radius() {
        return mem.getDouble(offset + 48L);
    }

    public void setRadius(double value) {
        mem.putDouble(offset + 48L, value);
    }

}
