// Auto-generated by `cargo run -p xtask -- gen-java`. Do NOT edit by hand.
package org.polaris2023.mps.ffi;

import org.polaris2023.mps_rigid_body.util.NativeMemory;

public final class Vec3 {
    public static final long SIZEOF = 24L;

    private final NativeMemory mem;
    private final long offset;

    public Vec3(NativeMemory mem, long offset) {
        this.mem = mem;
        this.offset = offset;
    }

    public static long sizeOf() {
        return SIZEOF;
    }

    public NativeMemory mem() {
        return mem;
    }

    public long offset() {
        return offset;
    }

    public double x() {
        return mem.getDouble(offset + 0L);
    }

    public void setX(double value) {
        mem.putDouble(offset + 0L, value);
    }

    public double y() {
        return mem.getDouble(offset + 8L);
    }

    public void setY(double value) {
        mem.putDouble(offset + 8L, value);
    }

    public double z() {
        return mem.getDouble(offset + 16L);
    }

    public void setZ(double value) {
        mem.putDouble(offset + 16L, value);
    }

}
