// Auto-generated by `cargo run -p xtask -- gen-java`. Do NOT edit by hand.
package org.polaris2023.mps.ffi;

import org.polaris2023.mps_rigid_body.util.NativeMemory;

public final class VoxelBuildStats {
    public static final long SIZEOF = 36L;

    private final NativeMemory mem;
    private final long offset;

    public VoxelBuildStats(NativeMemory mem, long offset) {
        this.mem = mem;
        this.offset = offset;
    }

    public static long sizeOf() {
        return SIZEOF;
    }

    public NativeMemory mem() {
        return mem;
    }

    public long offset() {
        return offset;
    }

    public int cellCount() {
        return mem.getInt(offset + 0L);
    }

    public void setCellCount(int value) {
        mem.putInt(offset + 0L, value);
    }

    public int solidCount() {
        return mem.getInt(offset + 4L);
    }

    public void setSolidCount(int value) {
        mem.putInt(offset + 4L, value);
    }

    public int selectedMode() {
        return mem.getInt(offset + 8L);
    }

    public void setSelectedMode(int value) {
        mem.putInt(offset + 8L, value);
    }

    public int estimatedParts() {
        return mem.getInt(offset + 12L);
    }

    public void setEstimatedParts(int value) {
        mem.putInt(offset + 12L, value);
    }

    public int estimatedVertices() {
        return mem.getInt(offset + 16L);
    }

    public void setEstimatedVertices(int value) {
        mem.putInt(offset + 16L, value);
    }

    public int estimatedTriangles() {
        return mem.getInt(offset + 20L);
    }

    public void setEstimatedTriangles(int value) {
        mem.putInt(offset + 20L, value);
    }

    public int sizeX() {
        return mem.getInt(offset + 24L);
    }

    public void setSizeX(int value) {
        mem.putInt(offset + 24L, value);
    }

    public int sizeY() {
        return mem.getInt(offset + 28L);
    }

    public void setSizeY(int value) {
        mem.putInt(offset + 28L, value);
    }

    public int sizeZ() {
        return mem.getInt(offset + 32L);
    }

    public void setSizeZ(int value) {
        mem.putInt(offset + 32L, value);
    }

}
