// Auto-generated by `cargo run -p xtask -- gen-java`. Do NOT edit by hand.
package org.polaris2023.mps.ffi;

public final class VoxelColliderMode {
    private VoxelColliderMode() {}

    public static final int AUTO = 0;
    public static final int CUBOIDS = 1;
    public static final int GREEDY_CUBOIDS = 2;
    public static final int SURFACE_MESH = 3;

    public static int fromRaw(int raw) {
        return raw;
    }

    public static int toRaw(int value) {
        return value;
    }
}
