// Auto-generated by `cargo run -p xtask -- gen-java`. Do NOT edit by hand.
package org.polaris2023.mps.ffi;

import org.polaris2023.mps_rigid_body.util.NativeMemory;

public final class VoxelColliderOptions {
    public static final long SIZEOF = 16L;

    private final NativeMemory mem;
    private final long offset;

    public VoxelColliderOptions(NativeMemory mem, long offset) {
        this.mem = mem;
        this.offset = offset;
    }

    public static long sizeOf() {
        return SIZEOF;
    }

    public NativeMemory mem() {
        return mem;
    }

    public long offset() {
        return offset;
    }

    public int mode() {
        return mem.getInt(offset + 0L);
    }

    public void setMode(int value) {
        mem.putInt(offset + 0L, value);
    }

    public boolean dynamicBody() {
        return mem.getBool(offset + 4L);
    }

    public void setDynamicBody(boolean value) {
        mem.putByte(offset + 4L, value ? 1 : 0);
    }

    public int smallVoxelLimit() {
        return mem.getInt(offset + 8L);
    }

    public void setSmallVoxelLimit(int value) {
        mem.putInt(offset + 8L, value);
    }

    public int meshVoxelLimit() {
        return mem.getInt(offset + 12L);
    }

    public void setMeshVoxelLimit(int value) {
        mem.putInt(offset + 12L, value);
    }

}
