[package]
name = "mps-jni"
version.workspace = true
edition.workspace = true

[lib]
name = "mps_rigid_body"
crate-type = ["cdylib", "rlib"]

[features]
anvilkit-bridge = ["mps-core/anvilkit-bridge"]

[dependencies]
mps-formula = { path = "../mps-formula" }
ljni = { workspace = true }
mps-core = { path = "../mps-core" }
mps-ffm = { path = "../mps-ffm" }