// Auto-generated by `cargo run -p xtask -- dump-metrics`.
// Do NOT edit by hand — re-run the command above after large changes
// (OPTIMIZATION.md §N3).
//
// Source of truth:
//   TEST_COUNT       = `grep -rh '#[test]' crates/mps-test/src/ | wc -l`
//   JNI_METHOD_COUNT= `grep -cE 'jni!\\(|jni_e_c!\\(' crates/mps-jni/src/lib.rs`
//   CORE_FFI_COUNT  = `grep -rhE '^pub extern "C"' crates/mps-core/src/rapier/ | wc -l`

/// Total number of `#[test]` items in `mps-test`, as a `&'static str` so it
/// can be inserted into `view!` literals directly (`{ (TEST_COUNT) }`).
pub const TEST_COUNT: &str = "588";
/// Total number of `jni!(`/`jni_e_c!(` method entries in `mps-jni`.
pub const JNI_METHOD_COUNT: &str = "290";
/// Total number of `pub extern "C" fn` declarations in `mps-core/rapier`.
pub const CORE_FFI_COUNT: &str = "453";
