// Auto-generated by `cargo run -p xtask -- dump-metrics`.
// Do NOT edit by hand — re-run the command above after large changes
// (OPTIMIZATION.md §N3).
//
// Source of truth:
//   TEST_COUNT       = `grep -rh '#[test]' crates/mps-test/src/ | wc -l`
//   JNI_METHOD_COUNT= `grep -cE 'jni!\\(|jni_e_c!\\(' crates/mps-jni/src/lib.rs`
//   CORE_FFI_COUNT  = `grep -rhE '^pub extern "C"' crates/mps-core/src/rapier/ | wc -l`

/// Total number of `#[test]` items in `mps-test`, as a `&'static str` so it
/// can be inserted into `view!` literals directly (`{ (TEST_COUNT) }`).
pub const TEST_COUNT: &str = "712";
/// Total number of `jni!(`/`jni_e_c!(` method entries in `mps-jni`.
pub const JNI_METHOD_COUNT: &str = "314";
/// Total number of `pub extern "C" fn` declarations in `mps-core/rapier`.
pub const CORE_FFI_COUNT: &str = "488";

/// Per-subsystem FFI breakdown by function-name prefix (manual; not regenerated by dump-metrics).
/// Re-add after running `cargo run -p xtask -- dump-metrics` if wiped (pitfall #5).
/// Counts from: grep -rhE '^pub extern "C" fn' crates/mps-core/src/rapier/ | sed -E 's/^pub extern "C" fn ([a-z_]+).*/\1/' | awk -F_ '{print $1}' | sort | uniq -c
pub const FFI_WORLD: &str = "108";
pub const FFI_RIGID_BODY: &str = "62";
pub const FFI_COLLIDER: &str = "70";
pub const FFI_QUERY: &str = "58";

/// Formula-module count (manual count of physics/astro/math modules in
/// `crates/mps-formula/src/` excluding lib/error/math/celestial_data/ffi):
/// 31 single-file modules + 2 directory modules (rotor/, spaceflight/) = 33.
/// Re-add after running `cargo run -p xtask -- dump-metrics` if wiped (pitfall #5).
pub const FORMULA_MODULE_COUNT: &str = "33";

/// Celestial-body count — `pub static` bodies in celestial_data.rs:
/// Sun + Mercury + Venus + Earth + Moon + Mars + Jupiter + Saturn +
/// Uranus + Neptune = 10.
/// Re-add after running `cargo run -p xtask -- dump-metrics` if wiped (pitfall #5).
pub const CELESTIAL_COUNT: &str = "10";

/// Distinct gravity-model `pub fn`s in gravitational_models.rs
/// (spherical_harmonics / ellipsoid / quadrupole_tensor / quadrupole_from_j2
/// / zonal_harmonics — carlson_rf / carlson_rd are elliptic helpers, not models).
/// Re-add after running `cargo run -p xtask -- dump-metrics` if wiped (pitfall #5).
pub const GRAVITY_MODEL_COUNT: &str = "5";

/// Symplectic-integrator `pub fn`s in integrators.rs, EXCLUDING helper fns
/// (energy / phase / Mortono-style adaptive steppers etc).
/// Re-add after running `cargo run -p xtask -- dump-metrics` if wiped (pitfall #5).
pub const INTEGRATOR_COUNT: &str = "6";

/// Workspace version (manual; matches mps-web Cargo.toml version).
/// Re-add after running `cargo run -p xtask -- dump-metrics` if wiped (pitfall #5).
pub const VERSION: &str = "0.1.4";
