modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="Polaris Stars"
description='''
Java 25 FFM NeoForge preview for mps_rigid_body.
'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_forge_version},)"
ordering="NONE"
side="BOTH"
