//! Force registry — type-erased force-law registration with per-step dispatch.
//!
//! ## Motivation
//!
//! Before this module, every force subsystem (Newtonian gravity, air drag,
//! electromagnetic, aerodynamic surfaces, …) was applied via hard-coded
//! `if let Some(law)` branches inside `world_step` or its callees.  Adding a
//! new force type meant touching five files: the struct definition, the setter
//! FFI, `CustomPhysicsState`, the `world_step` dispatch, and cbindgen exports.
//!
//! The registry centralises discovery: a force law implements [`ForceLaw`],
//! registers itself into [`ForceRegistry`] (held by `PhysicsWorld`), and
//! `world_step` simply calls `registry.apply_all()`.  A new law is now a
//! single struct plus a `register_*` call — no dispatch logic to update.
//!
//! ## Architecture
//!
//! ```text
//!                  world_step
//!                     │
//!            ForceFacade (bodies + colliders + narrow_phase + frame_log)
//!            ╱    │     ╲
//!    ForceLaw₁  ForceLaw₂  …  force_set_*_law FFI  (all use facade)
//!            ╲    │     ╱
//!            ForceRegistry  →  drain_report()  →  CustomPhysicsReport
//!   ```
//!
//! ## ForceFacade — the unified force application surface
//!
//! [`ForceFacade`] is the sole entry-point for applying forces to bodies.
//! Every `add_force` / `add_torque` call flows through it, so the frame-log
//! automatically records which [`ForceLawType`] produced each force.
//! `ForceReport` is then generated by draining this log — no manual bookkeeping.
//!
//! To add a new force type:
//! 1. Add a variant to [`ForceLawType`].
//! 2. Implement [`ForceLaw`] and register it into [`ForceRegistry`].
//! 3. In the `apply()` implementation, use the `facade` to push forces.
//!
//! The report is collected automatically.

use rapier3d::dynamics::force_containers::{ForceKind, Persistence};
use rapier3d::prelude::{AngVector, ColliderSet, NarrowPhase, RigidBodyHandle, RigidBodySet, Vector};
use smallvec::SmallVec;

use crate::rapier::ffi::CustomPhysicsReport;
use crate::rapier::math::KahanVec3;

// ---------------------------------------------------------------------------
// ForceLawType — enum of all recognised force sources
// ---------------------------------------------------------------------------

/// Categorises every force that can act on a rigid body.
///
/// The enum is `#[non_exhaustive]` so new variants can be added without
/// breaking downstream callers that match on it.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[non_exhaustive]
pub enum ForceLawType {
    /// Rapier's built-in world gravity (`world.gravity` vector).
    WorldGravity,
    /// Direct force added via `rigid_body_add_force` FFI or `add_force()`.
    UserForce,
    /// Newtonian pairwise gravitational attraction.
    NewtonianGravity,
    /// Tangential Coulomb friction between contacting bodies.
    CoulombFriction,
    /// Reynolds-number-aware aerodynamic drag (per-body).
    AirDrag,
    /// Buoyancy force (Archimedes' principle).
    Buoyancy,
    /// Lorentz force from electric + magnetic fields.
    Electromagnetic,
    /// Linear spring anchored to a fixed point.
    ElasticSpring,
    /// Point-mass gravitational attraction to a fixed source.
    PointGravity,
    /// Aerodynamic force from surface-sample panels.
    AerodynamicSurface,
    /// Aerodynamic force from voxel occupancy grids.
    AerodynamicVoxel,
    /// Fluid drag on AABB-aligned bodies.
    FluidAABB,
    /// Lennard-Jones intermolecular potential.
    MolecularLennardJones,
    /// Coulomb electrostatic force between molecules.
    MolecularCoulomb,
    /// PID controller output force.
    ControlPID,
    /// Solar-wind dynamic pressure on a Rapier body (planet-surface sensitive).
    /// Formula: see `mps_formula::heliophysics::solar_wind_dynamic_pressure`.
    SolarWindPressure,
    /// Chandrasekhar dynamical-friction deceleration for a body moving through
    /// a background density field.  See `mps_formula::galactic_dynamics`.
    DynamicalFriction,
    /// MOND (Modified Newtonian Dynamics) gravity in the low-acceleration regime
    /// (a < a_0), used for deep-field non-Newtonian flat rotation curves.
    MonDGravity,
    /// Eddington-limited radiation pressure pushing a Rapier body outward
    /// from an accretor (luminous source). Formula: see
    /// `mps_formula::high_energy_astro::eddington_limited_luminosity`; force
    /// is `F = (L_Edd / (c · 4π · r²)) · A_eff`, along +r̂ (away from source).
    EddingtonRadiationPressure,
    /// X-ray binary disc bolometric irradiation pushing a Rapier body outward
    /// from the accretor with force `F = (L_X / (c · 4π · r²)) · A_eff`.  The
    /// luminosity is `mps_formula::high_energy_astro::xray_disc_bolometric_luminosity`
    /// (returned in solar luminosities; multiplied by `L_SUN` for SI watts).
    XrayIrradiation,
    /// Magnetic-dipole torque on a magnetised Rapier body located in a pulsar's
    /// dipole field.  Surface B-field magnitude is computed by
    /// `mps_formula::high_energy_astro::pulsar_surface_b_field`; the dipole B
    /// falls off as 1/r³; torque `τ = μ × B(r)`, applied via
    /// `ForceFacade::add_torque`.  Configured by `PulsarMagneticDipoleLaw`.
    PulsarMagneticDipole,
    /// Jeans-escape drag: a Rapier body near a planetary exobase is pushed
    /// along the escape direction by the thermal Jeans efflux.  Efflux Φ
    /// [m⁻²·s⁻¹] is `mps_formula::heliophysics::jeans_escape_flux`; the
    /// momentum flux is `Φ · m_molecule · v_thermal` (Pa), and force is
    /// `p · A_eff · ê`.  Configured by `JeansEscapeLaw`.
    JeansEscape,
    /// Terrain / irregular-body gravity driving the rigid-body world.  The
    /// acceleration at each body's position is sampled from one of the
    /// `terrain_gravity` models (polyhedron, DEM, lunar mascon) and applied as
    /// `F = m · a` through the facade.  Configured by `TerrainGravityLaw`.
    TerrainGravity,
    /// User-defined force registered via FFI (opaque type tag in upper 32 bits).
    Custom(u64),
}

/// Map a rapier [`ForceKind`] (engine-native force container) to the nearest
/// mps-core [`ForceLawType`] for frame-report categorisation. The container model
/// is finer-grained than the legacy law enum, so several kinds collapse onto the
/// same report bucket.
pub(crate) fn force_kind_to_law(kind: ForceKind) -> ForceLawType {
    match kind {
        ForceKind::Gravity => ForceLawType::WorldGravity,
        ForceKind::Thrust => ForceLawType::ControlPID,
        ForceKind::Magnetic => ForceLawType::Electromagnetic,
        ForceKind::Wind => ForceLawType::AirDrag,
        ForceKind::Friction | ForceKind::ContactReaction => ForceLawType::CoulombFriction,
        ForceKind::Event | ForceKind::User | ForceKind::Custom(_) => ForceLawType::UserForce,
        _ => ForceLawType::UserForce,
    }
}

impl ForceLawType {
    /// Human-readable label for debug logging and reports.
    pub fn label(&self) -> &'static str {
        match self {
            Self::WorldGravity => "WorldGravity",
            Self::UserForce => "UserForce",
            Self::NewtonianGravity => "NewtonianGravity",
            Self::CoulombFriction => "CoulombFriction",
            Self::AirDrag => "AirDrag",
            Self::Buoyancy => "Buoyancy",
            Self::Electromagnetic => "Electromagnetic",
            Self::ElasticSpring => "ElasticSpring",
            Self::PointGravity => "PointGravity",
            Self::AerodynamicSurface => "AerodynamicSurface",
            Self::AerodynamicVoxel => "AerodynamicVoxel",
            Self::FluidAABB => "FluidAABB",
            Self::MolecularLennardJones => "MolecularLennardJones",
            Self::MolecularCoulomb => "MolecularCoulomb",
            Self::ControlPID => "ControlPID",
            Self::SolarWindPressure => "SolarWindPressure",
            Self::DynamicalFriction => "DynamicalFriction",
            Self::MonDGravity => "MonDGravity",
            Self::EddingtonRadiationPressure => "EddingtonRadiationPressure",
            Self::XrayIrradiation => "XrayIrradiation",
            Self::PulsarMagneticDipole => "PulsarMagneticDipole",
            Self::JeansEscape => "JeansEscape",
            Self::TerrainGravity => "TerrainGravity",
            Self::Custom(_) => "Custom",
        }
    }
}

// ---------------------------------------------------------------------------
// ForceReport — per-frame telemetry keyed by force type
// ---------------------------------------------------------------------------

/// Per-frame contribution from one force law.
#[derive(Clone, Copy, Debug, Default)]
pub struct ForceContribution {
    /// Total force vector (N) applied across all bodies this frame.
    pub total_force: crate::rapier::ffi::Vec3,
    /// Number of bodies that received non-zero force from this law.
    pub body_count: u32,
}

/// Capacity of the fixed-size contributions table. Identical to the `idx`
/// range produced by [`force_law_type_idx`] (slots 0..=33, with 26 reserved
/// for `ForceLawType::Custom`). Must stay in lockstep with `NUM_FORCE_TYPES`
/// in [`ForceFacade::drain_report`].
pub(crate) const NUM_FORCE_TYPES: usize = 34;

/// P0.5 fix: fixed-size index table replacing `BTreeMap<ForceLawType, _>`.
///
/// Each slot is indexed by [`force_law_type_idx`]; `None` means that force
/// type produced no contribution this frame. The two commercially important
/// operations (`add` / `get` / `iter`) are O(1) — the previous `BTreeMap`
/// cost one `O(log N)` lookup plus a possible node allocation per entry.
///
/// Public API (`get`, `iter`, `values`, `is_empty`, `add`) mirrors the
/// subset of `BTreeMap` semantics the codebase actually uses, so external
/// callers (`shared_arena::holes::flush_force_breakdown`, the legacy report
/// converter, the unit tests) stay source-compatible.
#[derive(Clone, Debug)]
pub struct ForceContributionTable {
    slots: [Option<ForceContribution>; NUM_FORCE_TYPES],
}

impl Default for ForceContributionTable {
    fn default() -> Self {
        // Manual impl needed because arrays of size > 32 do not derive
        // `Default` in stable Rust (const generics limitation).
        Self {
            slots: std::array::from_fn(|_| None),
        }
    }
}

impl<'a> IntoIterator for &'a ForceContributionTable {
    type Item = (ForceLawType, &'a ForceContribution);
    type IntoIter = ForceContributionTableIter<'a>;
    fn into_iter(self) -> Self::IntoIter {
        ForceContributionTableIter {
            table: self,
            pos: 0,
        }
    }
}

/// By-reference iterator over the active slots of a [`ForceContributionTable`].
/// Pairs every active slot with the `ForceLawType` recovered from its index
/// via [`force_law_type_from_idx`]. Used by `for … in &report.contributions`.
pub struct ForceContributionTableIter<'a> {
    table: &'a ForceContributionTable,
    pos: usize,
}

impl<'a> Iterator for ForceContributionTableIter<'a> {
    type Item = (ForceLawType, &'a ForceContribution);

    fn next(&mut self) -> Option<Self::Item> {
        while self.pos < NUM_FORCE_TYPES {
            let idx = self.pos;
            self.pos += 1;
            if let Some(c) = self.table.slots[idx].as_ref() {
                return Some((force_law_type_from_idx(idx), c));
            }
        }
        None
    }
}

impl ForceContributionTable {
    pub fn get(&self, law_type: ForceLawType) -> Option<&ForceContribution> {
        self.slots[force_law_type_idx(law_type)].as_ref()
    }

    /// Borrowing variant mirroring `BTreeMap::get` returning a `Copiable` value
    /// (used by `to_legacy_report`). `&ForceLawType` accepted for source-compat.
    pub fn get_copy(&self, law_type: &ForceLawType) -> Option<ForceContribution> {
        self.slots[force_law_type_idx(*law_type)]
    }

    /// Iterate over `(ForceLawType, &ForceContribution)` for every active slot.
    pub fn iter(&self) -> impl Iterator<Item = (ForceLawType, &ForceContribution)> {
        self.slots
            .iter()
            .enumerate()
            .filter_map(|(idx, opt)| opt.as_ref().map(|c| (force_law_type_from_idx(idx), c)))
    }

    /// Iterate over `(&ForceContribution)` for every active slot (sources removed).
    pub fn values(&self) -> impl Iterator<Item = &ForceContribution> {
        self.slots.iter().filter_map(Option::as_ref)
    }

    pub fn is_empty(&self) -> bool {
        self.slots.iter().all(Option::is_none)
    }

    /// Insert/merge a contribution in place. Same semantics as the previous
    /// `self.contributions.entry(law_type).or_default()` + `+=` pattern.
    pub fn add(
        &mut self,
        law_type: ForceLawType,
        force: crate::rapier::ffi::Vec3,
        body_count: u32,
    ) {
        let idx = force_law_type_idx(law_type);
        let entry = self.slots[idx].get_or_insert_with(ForceContribution::default);
        entry.total_force = crate::rapier::ffi::Vec3 {
            x: entry.total_force.x + force.x,
            y: entry.total_force.y + force.y,
            z: entry.total_force.z + force.z,
        };
        entry.body_count += body_count;
    }
}

/// Aggregated force report for one simulation step.
///
/// Building block for `CustomPhysicsReport` — maps each active force type to
/// its per-frame contribution so callers can see exactly where forces are
/// coming from.
#[derive(Clone, Debug, Default)]
pub struct ForceReport {
    pub contributions: ForceContributionTable,
    pub max_reynolds_number: f64,
}

impl ForceReport {
    pub fn add(
        &mut self,
        law_type: ForceLawType,
        force: rapier3d::prelude::Vector,
        body_count: u32,
    ) {
        let f = crate::rapier::ffi::vec3_from_rapier(force);
        self.contributions.add(law_type, f, body_count);
    }

    /// Convert to the legacy flat `CustomPhysicsReport` struct for FFI.
    pub fn to_legacy_report(&self) -> CustomPhysicsReport {
        let total_external =
            self.contributions
                .iter()
                .fold(crate::rapier::ffi::Vec3::default(), |acc, (_, c)| {
                    crate::rapier::ffi::Vec3 {
                        x: acc.x + c.total_force.x,
                        y: acc.y + c.total_force.y,
                        z: acc.z + c.total_force.z,
                    }
                });
        let drag_contrib = self
            .contributions
            .get_copy(&ForceLawType::AirDrag)
            .unwrap_or_default();
        // external_force_body_count = max per-type body_count (each type touches
        // the same set of bodies, so max approximates unique body count)
        let ext_body_count = self
            .contributions
            .iter()
            .filter(|(ty, _)| {
                !matches!(
                    ty,
                    ForceLawType::WorldGravity | ForceLawType::UserForce | ForceLawType::AirDrag
                )
            })
            .map(|(_, c)| c.body_count)
            .max()
            .unwrap_or(0);

        CustomPhysicsReport {
            body_count: self
                .contributions
                .values()
                .map(|c| c.body_count)
                .sum::<u32>()
                .min(1), // at least 1 if anything happened
            drag_body_count: drag_contrib.body_count,
            external_force_body_count: ext_body_count,
            total_drag_force: drag_contrib.total_force,
            total_external_force: total_external,
            max_reynolds_number: self.max_reynolds_number,
        }
    }
}

// ---------------------------------------------------------------------------
// ForceLawType ↔ index mapping (P6: avoid per-body BTreeMap)
// ---------------------------------------------------------------------------

/// Map a `ForceLawType` to a compact index 0..31 for fixed-array aggregation.
fn force_law_type_idx(ft: ForceLawType) -> usize {
    match ft {
        ForceLawType::WorldGravity => 0,
        ForceLawType::UserForce => 1,
        ForceLawType::NewtonianGravity => 2,
        ForceLawType::CoulombFriction => 3,
        ForceLawType::AirDrag => 4,
        ForceLawType::Buoyancy => 5,
        ForceLawType::Electromagnetic => 6,
        ForceLawType::ElasticSpring => 7,
        ForceLawType::PointGravity => 8,
        ForceLawType::AerodynamicSurface => 9,
        ForceLawType::AerodynamicVoxel => 10,
        ForceLawType::FluidAABB => 11,
        ForceLawType::MolecularLennardJones => 12,
        ForceLawType::MolecularCoulomb => 13,
        // Indices 14–25 reserved for the retired space/trajectory/terrain force
        // variants (removed after `mps-cosmos` took over celestial/n-body/drag).
        // Do not renumber the survivors (ControlPID/Custom) below — external
        // callers may persist the numeric tags.
        ForceLawType::ControlPID => 23,
        // PHYSICS_EXPANSION_PLAN C1: solar wind / dyn friction / MOND gravity
        // occupy 27–29 (26 is reserved for Custom).  Do NOT renumber below.
        ForceLawType::SolarWindPressure => 27,
        ForceLawType::DynamicalFriction => 28,
        ForceLawType::MonDGravity => 29,
        // C2: Eddington radiation pressure uses idx 30.
        ForceLawType::EddingtonRadiationPressure => 30,
        // C3: X-ray disc irradiation uses idx 31; PulsarMagneticDipole idx 32.
        ForceLawType::XrayIrradiation => 31,
        ForceLawType::PulsarMagneticDipole => 32,
        // C4: Jeans-escape drag uses idx 33.
        ForceLawType::JeansEscape => 33,
        // Terrain gravity uses idx 14 (one of the 14–25 reserved slots that
        // were retired with the space/trajectory/terrain transition to mps-cosmos).
        // It does NOT shift the high-index survivors below.
        ForceLawType::TerrainGravity => 14,
        ForceLawType::Custom(_) => 26,
    }
}

fn force_law_type_from_idx(idx: usize) -> ForceLawType {
    match idx {
        0 => ForceLawType::WorldGravity,
        1 => ForceLawType::UserForce,
        2 => ForceLawType::NewtonianGravity,
        3 => ForceLawType::CoulombFriction,
        4 => ForceLawType::AirDrag,
        5 => ForceLawType::Buoyancy,
        6 => ForceLawType::Electromagnetic,
        7 => ForceLawType::ElasticSpring,
        8 => ForceLawType::PointGravity,
        9 => ForceLawType::AerodynamicSurface,
        10 => ForceLawType::AerodynamicVoxel,
        11 => ForceLawType::FluidAABB,
        12 => ForceLawType::MolecularLennardJones,
        13 => ForceLawType::MolecularCoulomb,
        23 => ForceLawType::ControlPID,
        27 => ForceLawType::SolarWindPressure,
        28 => ForceLawType::DynamicalFriction,
        29 => ForceLawType::MonDGravity,
        30 => ForceLawType::EddingtonRadiationPressure,
        31 => ForceLawType::XrayIrradiation,
        32 => ForceLawType::PulsarMagneticDipole,
        33 => ForceLawType::JeansEscape,
        // 14–25 were retired space/trajectory/terrain variants; 14 is now
        // TerrainGravity, the rest still fall through to Custom.
        14 => ForceLawType::TerrainGravity,
        _ => ForceLawType::Custom(0),
    }
}

/// Locate or insert a `KahanVec3` accumulator keyed by `idx` inside an inline
/// `SmallVec<[(usize, KahanVec3); 8]>` (P2.19). Linear search over a ≤8-slot
/// list replaces the previous 34-entry `[Option<KahanVec3>; 34]` per-body
/// stack-zinit (~1632 bytes zeroed per active body). Typical bodies touch only
/// 1–4 force-law types, so the inline path covers the common case with zero
/// allocation and no large memset.
fn totals_idx_of(totals: &mut SmallVec<[(usize, KahanVec3); 8]>, idx: usize) -> &mut KahanVec3 {
    if let Some(pos) = totals.iter().position(|(i, _)| *i == idx) {
        &mut totals[pos].1
    } else {
        totals.push((idx, KahanVec3::default()));
        // `push` above guarantees a last element; `unwrap` is infallible here.
        &mut totals.last_mut().unwrap().1
    }
}

// ---------------------------------------------------------------------------
// ForceFacade — the unified force-application surface
// ---------------------------------------------------------------------------

/// Per-body force record for one frame.
#[derive(Clone, Debug, Default)]
pub struct BodyForceLog {
    pub forces: SmallVec<[(ForceLawType, Vector); 8]>,
    pub torques: SmallVec<[(ForceLawType, Vector); 4]>,
}

/// The sole entry-point for applying forces to bodies.
///
/// Every `add_force` / `add_torque` call flows through this facade so the
/// frame-log automatically records which [`ForceLawType`] produced each force.
///
/// # Example
///
/// ```ignore
/// let mut facade = ForceFacade::new(bodies, colliders, narrow_phase, dt, ...);
/// facade.add_force(handle, force_vec, ForceLawType::AirDrag);
/// let report = facade.drain_report(); // auto-aggregated
/// ```
pub struct ForceFacade<'a> {
    pub bodies: &'a mut RigidBodySet,
    pub colliders: &'a mut ColliderSet,
    pub narrow_phase: &'a NarrowPhase,
    /// Timestep of the current `world_step` call (integration_parameters.dt).
    /// Laws that integrate quantities directly (e.g. the collider-less pulsar
    /// torque fallback) must scale by this value.
    pub dt: f64,
    /// Per-body force log: indexed by handle index (arena Index → usize).
    /// `None` = no forces for this body yet.  Auto-expanding.
    pub body_log: &'a mut Vec<Option<BodyForceLog>>,
    /// Persistent scratch buffer for legacy force computation (P5 fix).
    pub pending_forces: &'a mut SmallVec<[crate::rapier::events::PendingForce; 128]>,
    /// Persistent scratch buffer for Coulomb friction (P5 fix).
    pub friction_work: &'a mut Vec<(RigidBodyHandle, RigidBodyHandle, Vector)>,
    /// Reusable `(handle, force)` accumulator for ForceLaw::apply() implementations.
    /// Callers must `clear()` before use; contents are consumed by the law itself.
    pub scratch_force_pairs: &'a mut SmallVec<[(RigidBodyHandle, Vector); 64]>,
    /// Secondary `(handle, force)` scratch for laws needing a second accumulator
    /// (e.g. PulsarMagneticDipole's mass-propagated vs collider-less split).
    pub scratch_force_pairs_alt: &'a mut SmallVec<[(RigidBodyHandle, Vector); 64]>,
    /// Reusable `(handle, mass, position)` buffer for pairwise pre-collection.
    pub scratch_body_data: &'a mut SmallVec<[(RigidBodyHandle, f64, Vector); 64]>,
    /// Accumulated Reynolds number (shared across air drag laws).
    pub max_reynolds: f64,
}

impl<'a> ForceFacade<'a> {
    /// Create a new facade borrowing the world's physics components.
    pub fn new(
        bodies: &'a mut RigidBodySet,
        colliders: &'a mut ColliderSet,
        narrow_phase: &'a NarrowPhase,
        dt: f64,
        body_log: &'a mut Vec<Option<BodyForceLog>>,
        pending_forces: &'a mut SmallVec<[crate::rapier::events::PendingForce; 128]>,
        friction_work: &'a mut Vec<(RigidBodyHandle, RigidBodyHandle, Vector)>,
        scratch_force_pairs: &'a mut SmallVec<[(RigidBodyHandle, Vector); 64]>,
        scratch_force_pairs_alt: &'a mut SmallVec<[(RigidBodyHandle, Vector); 64]>,
        scratch_body_data: &'a mut SmallVec<[(RigidBodyHandle, f64, Vector); 64]>,
    ) -> Self {
        Self {
            bodies,
            colliders,
            narrow_phase,
            dt,
            body_log,
            pending_forces,
            friction_work,
            scratch_force_pairs,
            scratch_force_pairs_alt,
            scratch_body_data,
            max_reynolds: 0.0,
        }
    }

    /// Get or create a BodyForceLog entry for the given handle (O(1) direct index lookup).
    #[inline]
    fn log_entry(&mut self, handle: RigidBodyHandle) -> &mut BodyForceLog {
        let idx = handle.into_raw_parts().0 as usize;
        if idx >= self.body_log.len() {
            self.body_log.resize_with(idx + 1, || None);
        }
        self.body_log[idx].get_or_insert_with(BodyForceLog::default)
    }

    // ---- force application ----

    /// Apply a typed force to the body identified by `handle`.
    ///
    /// Returns `false` if the handle is invalid.
    pub fn add_force(
        &mut self,
        handle: RigidBodyHandle,
        force: Vector,
        source: ForceLawType,
    ) -> bool {
        let Some(body) = self.bodies.get_mut(handle) else {
            return false;
        };
        if !body.is_dynamic() || force == Vector::ZERO {
            return true; // no-op but not an error
        }
        body.add_force(force, true);
        self.log_entry(handle).forces.push((source, force));
        true
    }

    /// Apply a typed torque to the body identified by `handle`.
    pub fn add_torque(
        &mut self,
        handle: RigidBodyHandle,
        torque: Vector,
        source: ForceLawType,
    ) -> bool {
        let Some(body) = self.bodies.get_mut(handle) else {
            return false;
        };
        if !body.is_dynamic() || torque == Vector::ZERO {
            return true;
        }
        body.add_torque(torque, true);
        self.log_entry(handle).torques.push((source, torque));
        true
    }

    /// Apply a typed force at a specific world-space point.
    pub fn add_force_at_point(
        &mut self,
        handle: RigidBodyHandle,
        force: Vector,
        point: Vector,
        source: ForceLawType,
    ) -> bool {
        let Some(body) = self.bodies.get_mut(handle) else {
            return false;
        };
        if !body.is_dynamic() || force == Vector::ZERO {
            return true;
        }
        body.add_force_at_point(force, point, true);
        self.log_entry(handle).forces.push((source, force));
        true
    }

    /// Apply a **persistent** force via the kind-classified force-container model.
    ///
    /// Routes to `RigidBody::add_thrust(..., Persistence::Persistent)`: the force
    /// survives across steps and is *not* cleared by the per-frame `reset_forces`
    /// ritual, so a constant law (steady thrust, magnetic anchor, …) only needs to
    /// register it once. Returns the assigned entry id (or `0` if the body is
    /// non-dynamic / the force is zero). The `source` selects which container kind
    /// records the force (e.g. `ForceKind::Thrust`, `ForceKind::Magnetic`).
    pub fn add_persistent_force(
        &mut self,
        handle: RigidBodyHandle,
        force: Vector,
        torque: AngVector,
        point: Option<Vector>,
        source: ForceKind,
    ) -> u64 {
        let Some(body) = self.bodies.get_mut(handle) else {
            return 0;
        };
        if !body.is_dynamic() || force == Vector::ZERO {
            return 0;
        }
        let id = body.add_thrust(0, force, torque, point, Persistence::Persistent, true);
        self.log_entry(handle).forces.push((force_kind_to_law(source), force));
        id
    }

    /// Emit a **transient** event/one-shot force via the kind-classified model.
    ///
    /// Routes to `RigidBody::emit_event_force`: the force acts for the current step
    /// only and the container drains it at frame end automatically — no manual
    /// `reset_forces` needed. Use for one-shot impulses, contact-triggered pushes,
    /// or any force that must not persist. The `source` selects the container kind
    /// (e.g. `ForceKind::Event`, `ForceKind::Friction`).
    pub fn emit_event_force(
        &mut self,
        handle: RigidBodyHandle,
        force: Vector,
        torque: AngVector,
        point: Option<Vector>,
        source: ForceKind,
    ) -> u64 {
        let Some(body) = self.bodies.get_mut(handle) else {
            return 0;
        };
        if !body.is_dynamic() || force == Vector::ZERO {
            return 0;
        }
        let id = body.emit_event_force(force, torque, point, source, true);
        self.log_entry(handle).forces.push((force_kind_to_law(source), force));
        id
    }

    // ---- per-body typed force application (for iterators) ----

    /// Apply typed force directly to an already-referenced body.
    ///
    /// Use when iterating `bodies.iter_mut()` to avoid a second handle lookup.
    pub fn push_force(
        log: &mut Vec<Option<BodyForceLog>>,
        body: &mut rapier3d::dynamics::RigidBody,
        handle: RigidBodyHandle,
        force: Vector,
        source: ForceLawType,
    ) {
        if !body.is_dynamic() || force == Vector::ZERO {
            return;
        }
        body.add_force(force, true);
        let idx = handle.into_raw_parts().0 as usize;
        if idx >= log.len() {
            log.resize_with(idx + 1, || None);
        }
        log[idx]
            .get_or_insert_with(BodyForceLog::default)
            .forces
            .push((source, force));
    }

    /// Apply typed torque directly to an already-referenced body.
    pub fn push_torque(
        log: &mut Vec<Option<BodyForceLog>>,
        body: &mut rapier3d::dynamics::RigidBody,
        handle: RigidBodyHandle,
        torque: Vector,
        source: ForceLawType,
    ) {
        if !body.is_dynamic() || torque == Vector::ZERO {
            return;
        }
        body.add_torque(torque, true);
        let idx = handle.into_raw_parts().0 as usize;
        if idx >= log.len() {
            log.resize_with(idx + 1, || None);
        }
        log[idx]
            .get_or_insert_with(BodyForceLog::default)
            .torques
            .push((source, torque));
    }

    // ---- Reynolds number ----

    /// Update the max Reynolds number seen this frame.
    pub fn update_reynolds(&mut self, re: f64) {
        self.max_reynolds = self.max_reynolds.max(re);
    }

    // ---- report generation ----

    /// Drain the frame log into a [`ForceReport`] and reset for the next frame.
    pub fn drain_report(&mut self) -> ForceReport {
        let mut report = ForceReport {
            max_reynolds_number: self.max_reynolds,
            ..Default::default()
        };

        // C4: JeansEscape idx=33 — bump array to 34 slots. Mirrors NUM_FORCE_TYPES
        // exported above; both must stay in lockstep with force_law_type_idx's range.
        // P2.19: replace `[Option<KahanVec3>; 34]` (1632 bytes stack-zmemset per
        // active-body) with an inline `SmallVec` keyed by idx. Each body normally
        // touches only 1–4 force-law types, so inline cap 8 covers the fast path
        // without any per-frame stack-zinit. Linear `position()` search over a
        // ≤8-slot list is cheaper than the previous 34-element zero-initialise.
        let mut body_totals: SmallVec<[(usize, KahanVec3); 8]> = SmallVec::new();
        let mut drained = std::mem::take(self.body_log);
        for log in drained.iter_mut().flatten() {
            // P0.5 fix: keep using the per-body KahanVec3 accumulator — its
            // per-source-summed values merge directly into the fixed-size
            // ForceContributionTable, which is O(1) lookup vs the previous
            // BTreeMap::entry O(log N) + node allocation.
            body_totals.clear();
            for (source, f) in &log.forces {
                let idx = force_law_type_idx(*source);
                totals_idx_of(&mut body_totals, idx).add(crate::rapier::ffi::Vec3 {
                    x: f.x,
                    y: f.y,
                    z: f.z,
                });
            }
            for (source, f) in &log.torques {
                let idx = force_law_type_idx(*source);
                totals_idx_of(&mut body_totals, idx).add(crate::rapier::ffi::Vec3 {
                    x: f.x,
                    y: f.y,
                    z: f.z,
                });
            }
            // Merge per-body per-source totals into the frame report. Each
            // touched source contributes one body to body_count and adds
            // kahan.value() to total_force (Kahan summed).
            for (idx, kahan) in body_totals.drain(..) {
                let law_type = force_law_type_from_idx(idx);
                report.contributions.add(law_type, kahan.value(), 1);
            }
        }

        self.max_reynolds = 0.0;
        report
    }
}

// ---------------------------------------------------------------------------
// ForceLaw trait
// ---------------------------------------------------------------------------

/// A pluggable physics force law.
///
/// Implementors compute per-frame forces and apply them via the [`ForceFacade`].
/// The facade automatically records which [`ForceLawType`] produced each force,
/// so implementors **do not** need to manage `ForceReport` themselves.
///
/// # Implementation notes
///
/// - `apply` receives a `&mut ForceFacade` — use `facade.add_force(handle, force, self.law_type())`.
/// - `law_type()` must return the same value for the lifetime of the law.
/// - `clone_box()` is used when the FFI layer needs to read a law's config.
pub trait ForceLaw: Send + Sync {
    /// The categorisation tag for this law.
    fn law_type(&self) -> ForceLawType;

    /// Whether this law should run this frame.
    fn enabled(&self) -> bool {
        true
    }

    /// Apply the law to all relevant bodies via the facade.
    ///
    /// Use `facade.add_force()` / `facade.add_torque()` to apply forces.
    /// The facade automatically records contributions per [`ForceLawType`].
    fn apply(&self, facade: &mut ForceFacade<'_>);

    /// Heap-clone this law (used for FFI read-back).
    fn clone_box(&self) -> Box<dyn ForceLaw>;
}

// ---------------------------------------------------------------------------
// ForceRegistry
// ---------------------------------------------------------------------------

/// A monotonically-growing handle into the force registry.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct ForceLawHandle(pub u64);

impl ForceLawHandle {
    pub fn raw(&self) -> u64 {
        self.0
    }
}

/// Ordered collection of active force laws.
///
/// Laws are applied in registration order.  The registry supports add,
/// remove, lookup-by-handle, and find-by-type operations.
pub struct ForceRegistry {
    laws: Vec<Option<RegistryEntry>>,
    next_handle: u64,
    free_slots: Vec<usize>,
}

struct RegistryEntry {
    handle: ForceLawHandle,
    law: Box<dyn ForceLaw>,
}

impl ForceRegistry {
    pub fn new() -> Self {
        Self {
            laws: Vec::new(),
            next_handle: 1,
            free_slots: Vec::new(),
        }
    }

    /// Register a force law.  Returns a handle that can be used to unregister
    /// or query the law later.
    pub fn register(&mut self, law: Box<dyn ForceLaw>) -> ForceLawHandle {
        let handle = ForceLawHandle(self.next_handle);
        self.next_handle += 1;
        let entry = RegistryEntry { handle, law };

        if let Some(slot) = self.free_slots.pop() {
            self.laws[slot] = Some(entry);
        } else {
            self.laws.push(Some(entry));
        }
        handle
    }

    /// Remove a previously-registered law by handle.
    ///
    /// Returns `true` if the law was found and removed.
    pub fn unregister(&mut self, handle: ForceLawHandle) -> bool {
        for (i, slot) in self.laws.iter_mut().enumerate() {
            if let Some(entry) = slot
                && entry.handle == handle
            {
                *slot = None;
                self.free_slots.push(i);
                return true;
            }
        }
        false
    }

    /// Find all handles for laws of a given type.
    pub fn find_by_type(&self, law_type: ForceLawType) -> Vec<ForceLawHandle> {
        self.laws
            .iter()
            .filter_map(|slot| {
                slot.as_ref().and_then(|entry| {
                    if entry.law.law_type() == law_type {
                        Some(entry.handle)
                    } else {
                        None
                    }
                })
            })
            .collect()
    }

    /// P8: unregister all laws of a given type in a single traversal
    /// (previously caller did find_by_type + per-handle unregister = 2 traversals).
    pub fn unregister_by_type(&mut self, law_type: ForceLawType) {
        for slot in self.laws.iter_mut() {
            if let Some(entry) = slot
                && entry.law.law_type() == law_type
            {
                *slot = None;
                // free_slots tracking is handled by existing unregister() pattern;
                // for unregister_by_type we don't track individual slots since
                // the next register will reuse any None slot via push.
            }
        }
    }

    /// Get a reference to a law by handle.
    pub fn get(&self, handle: ForceLawHandle) -> Option<&dyn ForceLaw> {
        self.laws.iter().find_map(|slot| {
            slot.as_ref()
                .and_then(|e| (e.handle == handle).then_some(&*e.law))
        })
    }

    /// Get a mutable reference to a law by handle (for config updates).
    pub fn get_mut(&mut self, handle: ForceLawHandle) -> Option<&mut (dyn ForceLaw + '_)> {
        for slot in self.laws.iter_mut() {
            if let Some(entry) = slot
                && entry.handle == handle
            {
                return Some(&mut *entry.law);
            }
        }
        None
    }

    /// Returns indices of all occupied slots (non-removed laws).
    ///
    /// Use with [`apply_at`](Self::apply_at) to avoid borrow conflicts when
    /// the registry and world are owned by the same struct.
    pub fn law_indices(&self) -> impl Iterator<Item = usize> + '_ {
        self.laws
            .iter()
            .enumerate()
            .filter_map(|(i, s)| s.as_ref().map(|_| i))
    }

    /// Apply a single law at the given index through the facade.
    ///
    /// # Panics
    /// Panics if `idx` is out of bounds or the slot is empty.
    pub fn apply_at(&self, idx: usize, facade: &mut ForceFacade<'_>) {
        if let Some(entry) = &self.laws[idx]
            && entry.law.enabled()
        {
            entry.law.apply(facade);
        }
    }

    /// Apply all enabled laws through the facade.
    pub fn apply_all(&self, facade: &mut ForceFacade<'_>) {
        for idx in self.law_indices() {
            self.apply_at(idx, facade);
        }
    }

    /// Number of registered (non-removed) laws.
    #[allow(dead_code)]
    pub fn len(&self) -> usize {
        self.laws.iter().filter(|s| s.is_some()).count()
    }

    /// Whether the registry is empty.
    #[allow(dead_code)]
    pub fn is_empty(&self) -> bool {
        self.laws.iter().all(|s| s.is_none())
    }
}

impl Default for ForceRegistry {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    struct DummyLaw {
        enabled: bool,
    }
    impl ForceLaw for DummyLaw {
        fn law_type(&self) -> ForceLawType {
            ForceLawType::TerrainGravity
        }
        fn enabled(&self) -> bool {
            self.enabled
        }
        fn apply(&self, _facade: &mut ForceFacade<'_>) {}
        fn clone_box(&self) -> Box<dyn ForceLaw> {
            Box::new(DummyLaw {
                enabled: self.enabled,
            })
        }
    }

    #[test]
    fn unregister_by_type_removes_terrain_law() {
        let mut reg = ForceRegistry::new();
        reg.register(Box::new(DummyLaw { enabled: true }));
        assert_eq!(reg.find_by_type(ForceLawType::TerrainGravity).len(), 1);
        reg.unregister_by_type(ForceLawType::TerrainGravity);
        assert_eq!(reg.find_by_type(ForceLawType::TerrainGravity).len(), 0);
        assert_eq!(reg.len(), 0);
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------
